# Generated by Django 4.2.1 on 2024-07-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-paid_at',)},
        ),
    ]
