# Generated by Django 4.2.1 on 2024-06-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
