# Generated by Django 4.2.1 on 2024-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://i.pinimg.com/originals/20/05/e2/2005e27a39fa5f6d97b2e0a95233b2be.jpg', upload_to='profile_pics'),
        ),
    ]
