# Generated by Django 4.2.1 on 2024-07-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Arts', 'Arts'), ('Business', 'Business'), ('Enterpreneurship', 'Enterpreneurship'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Film', 'Film'), ('Food', 'Food'), ('Politics', 'Politics'), ('Health', 'Health'), ('Music', 'Music'), ('Science & Technology', 'Science & Technology'), ('Others', 'Others')], default='Others', max_length=50)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.ImageField(default='default.jpg', upload_to='event_images')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
