# Generated by Django 4.2.1 on 2024-06-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categories',
            new_name='category',
        ),
    ]
