# Generated by Django 4.2.1 on 2024-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_categories_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
