# Generated by Django 4.2.1 on 2024-07-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts'), ('business', 'Business'), ('concert', 'Concert'), ('education', 'Education'), ('fashion', 'Fashion'), ('film', 'Film'), ('health', 'Health'), ('music', 'Music'), ('politics', 'Politics'), ('scienceandtechnology', 'Science & Technology'), ('others', 'Others')], default='Others', max_length=50),
        ),
    ]
