# Generated by Django 4.2.1 on 2024-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
