# Generated by Django 4.2.1 on 2024-07-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
