# Generated by Django 4.2.1 on 2024-07-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
