# Generated by Django 4.2.1 on 2024-07-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickettype_delete_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='quantity',
            new_name='quantity_available',
        ),
    ]
