# Generated by Django 4.2.1 on 2024-06-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('created_at',)},
        ),
    ]
