# Generated by Django 4.2.1 on 2024-07-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='email',
            field=models.EmailField(default='dummy@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='first_name',
            field=models.CharField(default='First', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='last_name',
            field=models.CharField(default='Last', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype'),
        ),
    ]
