# Generated by Django 4.2.1 on 2024-07-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketpurchase_email_ticketpurchase_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ('-created_at',)},
        ),
    ]
